version: "3"

services:
  app:
    build: .
    environment:
      - MONGO_URI=mongodb://db:27017/smarthub
      - FILES_DIRECTORY=/app/saved-files
    volumes:
      - ./saved-files:/app/saved-files
    ports:
      - 26001:4000
    links:
      - db

  db:
    image: mongo:4.4.3
    restart: unless-stopped
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_DATABASE: smarthub
